production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 20 %>

development:
  adapter: postgresql
  host: localhost
  database: real_price_dev
  pool: 5
  port: 5432

test:
  adapter: postgresql
  host: localhost
  database: real_price_test
  port: 5432
